In [2]:
import pypsa
import pandas as pd
import matplotlib.pyplot as plt

Read base network

In [36]:
n_KE=pypsa.Network("/home/alex-charly/SSD/Kenya/pypsa-earth/results/Kenya/postnetworks/elec_s_2_ec_lcopt_Co2L0.00-3H_3H_2050_0.071_NZ_50export.nc")

WARNING:pypsa.io:The following Link have buses which are not defined:
Index(['H2 pipeline KE.10_1_AC -> KE.25_1_DC'], dtype='object', name='name')
INFO:pypsa.io:Imported network elec_s_2_ec_lcopt_Co2L0.00-3H_3H_2050_0.071_NZ_50export.nc has buses, carriers, generators, global_constraints, lines, links, loads, storage_units, stores

In [37]:
n_KE_geo=pypsa.Network("/home/alex-charly/SSD/Kenya/pypsa-earth/results/Kenya_geo/postnetworks/elec_s_2_ec_lcopt_Co2L0.00-3H_3H_2050_0.071_NZ_50export.nc")

WARNING:pypsa.io:The following Link have buses which are not defined:
Index(['H2 pipeline KE.10_1_AC -> KE.25_1_DC'], dtype='object', name='name')
INFO:pypsa.io:Imported network elec_s_2_ec_lcopt_Co2L0.00-3H_3H_2050_0.071_NZ_50export.nc has buses, carriers, generators, global_constraints, lines, links, loads, storage_units, stores

In [44]:
n_KE_geo_pot=pypsa.Network("/home/alex-charly/SSD/Kenya/pypsa-earth/results/Kenya_geo_pot/postnetworks/elec_s_2_ec_lcopt_Co2L0.00-144H_144H_2050_0.071_NZ_50export.nc")

WARNING:pypsa.io:The following Link have buses which are not defined:
Index(['H2 pipeline KE.10_1_AC -> KE.25_1_DC'], dtype='object', name='name')
INFO:pypsa.io:Imported network elec_s_2_ec_lcopt_Co2L0.00-144H_144H_2050_0.071_NZ_50export.nc has buses, carriers, generators, global_constraints, lines, links, loads, storage_units, stores

In [51]:
n_KE_geo_pot_50res_0co2=pypsa.Network("/home/alex-charly/SSD/Kenya/pypsa-earth/results/Kenya_geo_pot/postnetworks/elec_s_2_ec_lcopt_Co2L0.00-144H-RES0.5_144H_2050_0.071_NZ_50export.nc")

WARNING:pypsa.io:The following Link have buses which are not defined:
Index(['H2 pipeline KE.10_1_AC -> KE.25_1_DC'], dtype='object', name='name')
INFO:pypsa.io:Imported network elec_s_2_ec_lcopt_Co2L0.00-144H-RES0.5_144H_2050_0.071_NZ_50export.nc has buses, carriers, generators, global_constraints, lines, links, loads, storage_units, stores

In [52]:
n_KE_geo_pot_50res_50co2=pypsa.Network("/home/alex-charly/SSD/Kenya/pypsa-earth/results/Kenya_geo_pot/postnetworks/elec_s_2_ec_lcopt_Co2L0.50-144H-RES0.5_144H_2050_0.071_NZ_50export.nc")

WARNING:pypsa.io:The following Link have buses which are not defined:
Index(['H2 pipeline KE.10_1_AC -> KE.25_1_DC'], dtype='object', name='name')
INFO:pypsa.io:Imported network elec_s_2_ec_lcopt_Co2L0.50-144H-RES0.5_144H_2050_0.071_NZ_50export.nc has buses, carriers, generators, global_constraints, lines, links, loads, storage_units, stores

In [3]:
n_KE_geo_pot100res_100co2=pypsa.Network("/home/alex-charly/SSD/Kenya/pypsa-earth/results/Kenya_geo_pot/postnetworks/elec_s_2_ec_lcopt_Co2L1.00-144H-RES1.0_144H_2050_0.071_NZ_50export.nc")

WARNING:pypsa.io:The following Link have buses which are not defined:
Index(['H2 pipeline KE.10_1_AC -> KE.25_1_DC'], dtype='object', name='name')
INFO:pypsa.io:Imported network elec_s_2_ec_lcopt_Co2L1.00-144H-RES1.0_144H_2050_0.071_NZ_50export.nc has buses, carriers, generators, global_constraints, lines, links, loads, storage_units, stores

In [9]:
n_KE_geo_pot_80res_100co2=pypsa.Network("/home/alex-charly/SSD/Kenya/pypsa-earth/results/Kenya_geo_pot/postnetworks/elec_s_2_ec_lcopt_Co2L1.00-144H-RES0.75_144H_2050_0.071_NZ_50export.nc")

WARNING:pypsa.io:The following Link have buses which are not defined:
Index(['H2 pipeline KE.10_1_AC -> KE.25_1_DC'], dtype='object', name='name')
INFO:pypsa.io:Imported network elec_s_2_ec_lcopt_Co2L1.00-144H-RES0.75_144H_2050_0.071_NZ_50export.nc has buses, carriers, generators, global_constraints, lines, links, loads, storage_units, stores

In [10]:
n_KE_geo_pot_80res_100co2.statistics.energy_balance(comps=["Generator"])

component  carrier             bus_carrier
Generator  Combined-Cycle Gas  Ac                                         4.925100e-01
           Geothermal          Ac                                         2.253740e+06
           Offshore Wind (AC)  Ac                                         2.427400e-01
           Onshore Wind        Ac                                         6.278024e+05
           Run of River        Ac                                         1.000469e+06
           Solar               Ac                                         6.571199e+07
           gas                 gas                                        2.908190e+00
           load                Ac                                         9.100000e-04
                               Battery Storage                            9.000000e-04
                               Dc                                         3.000000e-05
                               Hydrogen Storage                           9.700000e-04
                               Li ion                                     8.500000e-04
                               biogas                                     8.500000e-04
                               biomass                                    3.000000e-05
                               co2 stored                                 4.000000e-05
                               home battery                               9.000000e-04
                               low voltage                                9.000000e-04
                               oil                                        8.400000e-04
                               process emissions                          3.000000e-05
                               residential rural heat                     9.000000e-04
                               residential rural water tanks              8.600000e-04
                               residential urban decentral heat           8.800000e-04
                               residential urban decentral water tanks    8.600000e-04
                               services rural heat                        8.600000e-04
                               services rural water tanks                 8.600000e-04
                               services urban decentral heat              9.000000e-04
                               services urban decentral water tanks       8.600000e-04
                               solid biomass for industry                 2.000000e-05
                               urban central heat                         8.900000e-04
                               urban central water tanks                  8.700000e-04
           oil                 oil                                        2.762959e+07
           solar rooftop       low voltage                                1.429525e+07
Name: generators, dtype: float64

In [39]:
n_KE.statistics()

                                                   Optimal Capacity  \
Generator Combined-Cycle Gas                           6.391000e+02
          Geothermal                                   3.840000e+02
          Offshore Wind (AC)                           2.060000e-03
          Onshore Wind                                 4.358175e+02
          Run of River                                 3.562597e+02
...                                                             ...
Store     residential urban decentral water tanks      2.150000e-03
          services rural water tanks                   2.160000e-03
          services urban decentral water tanks         2.170000e-03
          solid biomass                                2.043000e+08
          urban central water tanks                    2.551400e-01

                                                   Installed Capacity  \
Generator Combined-Cycle Gas                             6.391000e+02
          Geothermal                                     3.840000e+02
          Offshore Wind (AC)                             0.000000e+00
          Onshore Wind                                   4.358154e+02
          Run of River                                   3.562597e+02
...                                                               ...
Store     residential urban decentral water tanks        0.000000e+00
          services rural water tanks                     0.000000e+00
          services urban decentral water tanks           0.000000e+00
          solid biomass                                  2.043000e+08
          urban central water tanks                      0.000000e+00

                                                         Supply  Withdrawal  \
Generator Combined-Cycle Gas                       1.130930e+00     0.00000
          Geothermal                               3.363602e+06     0.00000
          Offshore Wind (AC)                       2.819570e+00     0.00000
          Onshore Wind                             8.509157e+05     0.00000
          Run of River                             9.997915e+05     0.00000
...                                                         ...         ...
Store     residential urban decentral water tanks  8.221000e-02     0.20635
          services rural water tanks               8.282000e-02     0.20874
          services urban decentral water tanks     6.569000e-02     0.19053
          solid biomass                            1.155658e+08     0.00000
          urban central water tanks                5.717330e+00     5.97460

                                                   Energy Balance  \
Generator Combined-Cycle Gas                         1.130930e+00
          Geothermal                                 3.363602e+06
          Offshore Wind (AC)                         2.819570e+00
          Onshore Wind                               8.509157e+05
          Run of River                               9.997915e+05
...                                                           ...
Store     residential urban decentral water tanks   -1.241400e-01
          services rural water tanks                -1.259200e-01
          services urban decentral water tanks      -1.248400e-01
          solid biomass                              1.155658e+08
          urban central water tanks                 -2.572600e-01

                                                   Transmission  \
Generator Combined-Cycle Gas                                0.0
          Geothermal                                        0.0
          Offshore Wind (AC)                                0.0
          Onshore Wind                                      0.0
          Run of River                                      0.0
...                                                         ...
Store     residential urban decentral water tanks           0.0
          services rural water tanks                        0.0
          services urban decentral water tanks              0.0
          solid biomass                                     0.0
          urban central water tanks                         0.0

                                                   Capacity Factor  \
Generator Combined-Cycle Gas                          2.034110e-07
          Geothermal                                  9.999294e-01
          Offshore Wind (AC)                          1.553398e-01
          Onshore Wind                                2.228834e-01
          Run of River                                3.203602e-01
...                                                            ...
Store     residential urban decentral water tanks     4.837209e-01
          services rural water tanks                  4.907407e-01
          services urban decentral water tanks        4.838710e-01
          solid biomass                               7.307717e-01
          urban central water tanks                   4.975700e-01

                                                    Curtailment  \
Generator Combined-Cycle Gas                       5.598515e+06
          Geothermal                               2.376142e+02
          Offshore Wind (AC)                       1.674300e+00
          Onshore Wind                             1.861753e+05
          Run of River                             6.782232e+02
...                                                         ...
Store     residential urban decentral water tanks  0.000000e+00
          services rural water tanks               0.000000e+00
          services urban decentral water tanks     0.000000e+00
          solid biomass                            0.000000e+00
          urban central water tanks                0.000000e+00

                                                   Capital Expenditure  \
Generator Combined-Cycle Gas                              5.398422e+07
          Geothermal                                      7.378936e+07
          Offshore Wind (AC)                              4.065029e+02
          Onshore Wind                                    4.763292e+07
          Run of River                                    9.652526e+07
...                                                                ...
Store     residential urban decentral water tanks         1.307888e+03
          services rural water tanks                      1.316783e+03
          services urban decentral water tanks            1.319947e+03
          solid biomass                                   0.000000e+00
          urban central water tanks                       1.407051e+03

                                                   Operational Expenditure  \
Generator Combined-Cycle Gas                                  5.339110e+01
          Geothermal                                          3.230025e+04
          Offshore Wind (AC)                                  6.913000e-02
          Onshore Wind                                        2.084733e+04
          Run of River                                        1.020677e+04
...                                                                    ...
Store     residential urban decentral water tanks            -1.240000e-03
          services rural water tanks                         -1.250000e-03
          services urban decentral water tanks               -1.230000e-03
          solid biomass                                       1.578430e+09
          urban central water tanks                          -2.570000e-03

                                                        Revenue  Market Value
Generator Combined-Cycle Gas                       4.406708e+01     38.692308
          Geothermal                               1.222502e+08     36.345033
          Offshore Wind (AC)                       1.201219e+02     42.843750
          Onshore Wind                             3.617204e+07     42.509539
          Run of River                             3.679899e+07     36.806669
...                                                         ...           ...
Store     residential urban decentral water tanks  6.881380e+00     79.000000
          services rural water tanks              -1.614960e+00    -18.000000
          services urban decentral water tanks    -2.412660e+00    -28.000000
          solid biomass                            1.578430e+09     13.658283
          urban central water tanks                4.304346e+02     75.600000

[111 rows x 12 columns]

In [43]:
n_KE_geo.statistics()

                                                   Optimal Capacity  \
Generator Combined-Cycle Gas                           6.391000e+02
          Geothermal                                   1.409918e+04
          Offshore Wind (AC)                           1.500000e-04
          Onshore Wind                                 4.358154e+02
          Run of River                                 3.562597e+02
...                                                             ...
Store     residential urban decentral water tanks      2.000000e-04
          services rural water tanks                   1.900000e-04
          services urban decentral water tanks         1.900000e-04
          solid biomass                                2.043000e+08
          urban central water tanks                    3.788000e-02

                                                   Installed Capacity  \
Generator Combined-Cycle Gas                             6.391000e+02
          Geothermal                                     3.840000e+02
          Offshore Wind (AC)                             0.000000e+00
          Onshore Wind                                   4.358154e+02
          Run of River                                   3.562597e+02
...                                                               ...
Store     residential urban decentral water tanks        0.000000e+00
          services rural water tanks                     0.000000e+00
          services urban decentral water tanks           0.000000e+00
          solid biomass                                  2.043000e+08
          urban central water tanks                      0.000000e+00

                                                         Supply  Withdrawal  \
Generator Combined-Cycle Gas                       7.734000e-02     0.00000
          Geothermal                               1.235060e+08     0.00000
          Offshore Wind (AC)                       2.062400e-01     0.00000
          Onshore Wind                             1.021456e+06     0.00000
          Run of River                             9.983372e+05     0.00000
...                                                         ...         ...
Store     residential urban decentral water tanks  3.420000e-03     0.01519
          services rural water tanks               2.220000e-03     0.01391
          services urban decentral water tanks     2.550000e-03     0.01412
          solid biomass                            1.137915e+08     0.00000
          urban central water tanks                2.412860e+00     2.45021

                                                   Energy Balance  \
Generator Combined-Cycle Gas                         7.734000e-02
          Geothermal                                 1.235060e+08
          Offshore Wind (AC)                         2.062400e-01
          Onshore Wind                               1.021456e+06
          Run of River                               9.983372e+05
...                                                           ...
Store     residential urban decentral water tanks   -1.177000e-02
          services rural water tanks                -1.169000e-02
          services urban decentral water tanks      -1.157000e-02
          solid biomass                              1.137915e+08
          urban central water tanks                 -3.735000e-02

                                                   Transmission  \
Generator Combined-Cycle Gas                                0.0
          Geothermal                                        0.0
          Offshore Wind (AC)                                0.0
          Onshore Wind                                      0.0
          Run of River                                      0.0
...                                                         ...
Store     residential urban decentral water tanks           0.0
          services rural water tanks                        0.0
          services urban decentral water tanks              0.0
          solid biomass                                     0.0
          urban central water tanks                         0.0

                                                   Capacity Factor  \
Generator Combined-Cycle Gas                          1.564700e-08
          Geothermal                                  9.999769e-01
          Offshore Wind (AC)                          1.333333e-01
          Onshore Wind                                2.675548e-01
          Run of River                                3.198942e-01
...                                                            ...
Store     residential urban decentral water tanks     5.000000e-01
          services rural water tanks                  5.263158e-01
          services urban decentral water tanks        5.263158e-01
          solid biomass                               7.351156e-01
          urban central water tanks                   4.865364e-01

                                                    Curtailment  \
Generator Combined-Cycle Gas                       5.598516e+06
          Geothermal                               2.858058e+03
          Offshore Wind (AC)                       1.259400e-01
          Onshore Wind                             1.563161e+04
          Run of River                             2.132538e+03
...                                                         ...
Store     residential urban decentral water tanks  0.000000e+00
          services rural water tanks               0.000000e+00
          services urban decentral water tanks     0.000000e+00
          solid biomass                            0.000000e+00
          urban central water tanks                0.000000e+00

                                                   Capital Expenditure  \
Generator Combined-Cycle Gas                              5.398422e+07
          Geothermal                                      2.709297e+09
          Offshore Wind (AC)                              2.999022e+01
          Onshore Wind                                    4.763270e+07
          Run of River                                    9.652526e+07
...                                                                ...
Store     residential urban decentral water tanks         1.200435e+02
          services rural water tanks                      1.183041e+02
          services urban decentral water tanks            1.186159e+02
          solid biomass                                   0.000000e+00
          urban central water tanks                       2.089179e+02

                                                   Operational Expenditure  \
Generator Combined-Cycle Gas                                  3.651160e+00
          Geothermal                                          1.186012e+06
          Offshore Wind (AC)                                  5.050000e-03
          Onshore Wind                                        2.501870e+04
          Run of River                                        1.019180e+04
...                                                                    ...
Store     residential urban decentral water tanks            -1.200000e-04
          services rural water tanks                         -1.200000e-04
          services urban decentral water tanks               -1.100000e-04
          solid biomass                                       1.554196e+09
          urban central water tanks                          -3.700000e-04

                                                        Revenue  Market Value
Generator Combined-Cycle Gas                       1.894630e+00     22.000000
          Geothermal                               2.710483e+09     21.946161
          Offshore Wind (AC)                       5.331220e+00     30.500000
          Onshore Wind                             2.341315e+07     22.921360
          Run of River                             2.227403e+07     22.311126
...                                                         ...           ...
Store     residential urban decentral water tanks  1.047830e+00           NaN
          services rural water tanks              -8.958000e-02           NaN
          services urban decentral water tanks    -1.589700e-01           NaN
          solid biomass                            1.554196e+09     13.658285
          urban central water tanks                1.132546e+02     46.178571

[111 rows x 12 columns]

In [46]:
n_KE_geo_pot.statistics()

                                                   Optimal Capacity  \
Generator Combined-Cycle Gas                           6.391000e+02
          Geothermal                                   1.000000e+04
          Offshore Wind (AC)                           7.100000e-04
          Onshore Wind                                 4.358163e+02
          Run of River                                 3.562597e+02
...                                                             ...
Store     residential urban decentral water tanks      8.300000e-04
          services rural water tanks                   8.000000e-04
          services urban decentral water tanks         8.300000e-04
          solid biomass                                2.043000e+08
          urban central water tanks                    8.650000e-02

                                                   Installed Capacity  \
Generator Combined-Cycle Gas                             6.391000e+02
          Geothermal                                     3.840000e+02
          Offshore Wind (AC)                             0.000000e+00
          Onshore Wind                                   4.358154e+02
          Run of River                                   3.562597e+02
...                                                               ...
Store     residential urban decentral water tanks        0.000000e+00
          services rural water tanks                     0.000000e+00
          services urban decentral water tanks           0.000000e+00
          solid biomass                                  2.043000e+08
          urban central water tanks                      0.000000e+00

                                                         Supply  Withdrawal  \
Generator Combined-Cycle Gas                       3.505900e-01     0.00000
          Geothermal                               5.867144e+07     0.00000
          Offshore Wind (AC)                       9.420200e-01     0.00000
          Onshore Wind                             7.354236e+05     0.00000
          Run of River                             9.998640e+05     0.00000
...                                                         ...         ...
Store     residential urban decentral water tanks  0.000000e+00     0.02247
          services rural water tanks               0.000000e+00     0.02140
          services urban decentral water tanks     0.000000e+00     0.02275
          solid biomass                            1.096618e+08     0.00000
          urban central water tanks                4.699000e-02     0.13262

                                                   Energy Balance  \
Generator Combined-Cycle Gas                         3.505900e-01
          Geothermal                                 5.867144e+07
          Offshore Wind (AC)                         9.420200e-01
          Onshore Wind                               7.354236e+05
          Run of River                               9.998640e+05
...                                                           ...
Store     residential urban decentral water tanks   -2.247000e-02
          services rural water tanks                -2.140000e-02
          services urban decentral water tanks      -2.275000e-02
          solid biomass                              1.096618e+08
          urban central water tanks                 -8.562000e-02

                                                   Transmission  \
Generator Combined-Cycle Gas                                0.0
          Geothermal                                        0.0
          Offshore Wind (AC)                                0.0
          Onshore Wind                                      0.0
          Run of River                                      0.0
...                                                         ...
Store     residential urban decentral water tanks           0.0
          services rural water tanks                        0.0
          services urban decentral water tanks              0.0
          solid biomass                                     0.0
          urban central water tanks                         0.0

                                                   Capacity Factor  \
Generator Combined-Cycle Gas                          6.258801e-08
          Geothermal                                  6.697653e-01
          Offshore Wind (AC)                          1.549296e-01
          Onshore Wind                                1.926327e-01
          Run of River                                3.203835e-01
...                                                            ...
Store     residential urban decentral water tanks     5.180723e-01
          services rural water tanks                  5.125000e-01
          services urban decentral water tanks        5.180723e-01
          solid biomass                               7.385107e-01
          urban central water tanks                   4.967630e-01

                                                    Curtailment  \
Generator Combined-Cycle Gas                       5.598516e+06
          Geothermal                               2.056382e+04
          Offshore Wind (AC)                       6.134400e-01
          Onshore Wind                             3.019806e+05
          Run of River                             6.057099e+02
...                                                         ...
Store     residential urban decentral water tanks  0.000000e+00
          services rural water tanks               0.000000e+00
          services urban decentral water tanks     0.000000e+00
          solid biomass                            0.000000e+00
          urban central water tanks                0.000000e+00

                                                   Capital Expenditure  \
Generator Combined-Cycle Gas                              5.398422e+07
          Geothermal                                      0.000000e+00
          Offshore Wind (AC)                              1.405189e+02
          Onshore Wind                                    4.763279e+07
          Run of River                                    9.652526e+07
...                                                                ...
Store     residential urban decentral water tanks         5.034308e+02
          services rural water tanks                      4.897542e+02
          services urban decentral water tanks            5.070730e+02
          solid biomass                                   0.000000e+00
          urban central water tanks                       4.770328e+02

                                                   Operational Expenditure  \
Generator Combined-Cycle Gas                                  1.655140e+01
          Geothermal                                          5.728821e+05
          Offshore Wind (AC)                                  2.310000e-02
          Onshore Wind                                        1.801675e+04
          Run of River                                        1.020751e+04
...                                                                    ...
Store     residential urban decentral water tanks            -2.200000e-04
          services rural water tanks                         -2.100000e-04
          services urban decentral water tanks               -2.200000e-04
          solid biomass                                       1.497792e+09
          urban central water tanks                          -8.500000e-04

                                                        Revenue  Market Value
Generator Combined-Cycle Gas                       8.190950e+00     23.500000
          Geothermal                               1.055038e+09     17.982133
          Offshore Wind (AC)                       2.751274e+01     28.545455
          Onshore Wind                             2.292296e+07     31.169737
          Run of River                             2.323180e+07     23.234962
...                                                         ...           ...
Store     residential urban decentral water tanks -3.768300e-01           NaN
          services rural water tanks              -1.087900e-01           NaN
          services urban decentral water tanks    -2.676700e-01           NaN
          solid biomass                            1.497792e+09     13.658285
          urban central water tanks                2.657400e+00     30.000000

[106 rows x 12 columns]

In [53]:
n_KE_geo_pot_50res_0co2.statistics()

                                                   Optimal Capacity  \
Generator Combined-Cycle Gas                           6.391000e+02
          Geothermal                                   3.840012e+02
          Offshore Wind (AC)                           1.100000e-03
          Onshore Wind                                 1.718422e+04
          Run of River                                 3.562597e+02
...                                                             ...
Store     residential urban decentral water tanks      7.500000e-04
          services rural water tanks                   7.600000e-04
          services urban decentral water tanks         7.400000e-04
          solid biomass                                2.043000e+08
          urban central water tanks                    7.613000e-02

                                                   Installed Capacity  \
Generator Combined-Cycle Gas                             6.391000e+02
          Geothermal                                     3.840000e+02
          Offshore Wind (AC)                             0.000000e+00
          Onshore Wind                                   4.358154e+02
          Run of River                                   3.562597e+02
...                                                               ...
Store     residential urban decentral water tanks        0.000000e+00
          services rural water tanks                     0.000000e+00
          services urban decentral water tanks           0.000000e+00
          solid biomass                                  2.043000e+08
          urban central water tanks                      0.000000e+00

                                                         Supply  Withdrawal  \
Generator Combined-Cycle Gas                       3.499700e-01     0.00000
          Geothermal                               3.698014e+05     0.00000
          Offshore Wind (AC)                       1.551300e+00     0.00000
          Onshore Wind                             4.623600e+07     0.00000
          Run of River                             3.524033e+04     0.00000
...                                                         ...         ...
Store     residential urban decentral water tanks  0.000000e+00     0.01964
          services rural water tanks               0.000000e+00     0.02073
          services urban decentral water tanks     0.000000e+00     0.01899
          solid biomass                            9.999534e+07     0.00000
          urban central water tanks                2.500000e-03     0.08071

                                                   Energy Balance  \
Generator Combined-Cycle Gas                         3.499700e-01
          Geothermal                                 3.698014e+05
          Offshore Wind (AC)                         1.551300e+00
          Onshore Wind                               4.623600e+07
          Run of River                               3.524033e+04
...                                                           ...
Store     residential urban decentral water tanks   -1.964000e-02
          services rural water tanks                -2.073000e-02
          services urban decentral water tanks      -1.899000e-02
          solid biomass                              9.999534e+07
          urban central water tanks                 -7.821000e-02

                                                   Transmission  \
Generator Combined-Cycle Gas                                0.0
          Geothermal                                        0.0
          Offshore Wind (AC)                                0.0
          Onshore Wind                                      0.0
          Run of River                                      0.0
...                                                         ...
Store     residential urban decentral water tanks           0.0
          services rural water tanks                        0.0
          services urban decentral water tanks              0.0
          solid biomass                                     0.0
          urban central water tanks                         0.0

                                                   Capacity Factor  \
Generator Combined-Cycle Gas                          6.258801e-08
          Geothermal                                  1.099340e-01
          Offshore Wind (AC)                          1.636364e-01
          Onshore Wind                                3.071470e-01
          Run of River                                1.129196e-02
...                                                            ...
Store     residential urban decentral water tanks     4.933333e-01
          services rural water tanks                  5.131579e-01
          services urban decentral water tanks        4.864865e-01
          solid biomass                               7.625561e-01
          urban central water tanks                   5.151714e-01

                                                    Curtailment  \
Generator Combined-Cycle Gas                       5.598516e+06
          Geothermal                               1.883978e+06
          Offshore Wind (AC)                       8.629600e-01
          Onshore Wind                             9.324364e+06
          Run of River                             9.652294e+05
...                                                         ...
Store     residential urban decentral water tanks  0.000000e+00
          services rural water tanks               0.000000e+00
          services urban decentral water tanks     0.000000e+00
          solid biomass                            0.000000e+00
          urban central water tanks                0.000000e+00

                                                   Capital Expenditure  \
Generator Combined-Cycle Gas                              5.398422e+07
          Geothermal                                      7.378960e+07
          Offshore Wind (AC)                              2.172795e+02
          Onshore Wind                                    1.878159e+09
          Run of River                                    9.652526e+07
...                                                                ...
Store     residential urban decentral water tanks         4.544199e+02
          services rural water tanks                      4.647753e+02
          services urban decentral water tanks            4.476445e+02
          solid biomass                                   0.000000e+00
          urban central water tanks                       4.198687e+02

                                                   Operational Expenditure  \
Generator Combined-Cycle Gas                                  1.652208e+01
          Geothermal                                          3.551157e+03
          Offshore Wind (AC)                                  3.805000e-02
          Onshore Wind                                        1.128407e+06
          Run of River                                        3.586492e+02
...                                                                    ...
Store     residential urban decentral water tanks            -2.000000e-04
          services rural water tanks                         -2.100000e-04
          services urban decentral water tanks               -1.900000e-04
          solid biomass                                       1.365765e+09
          urban central water tanks                          -7.800000e-04

                                                        Revenue  Market Value
Generator Combined-Cycle Gas                      -6.438500e-01     -1.750000
          Geothermal                               9.383574e+05      2.537463
          Offshore Wind (AC)                      -5.708750e+00     -3.611111
          Onshore Wind                            -2.953371e+08     -6.387600
          Run of River                             1.692319e+05      4.802221
...                                                         ...           ...
Store     residential urban decentral water tanks -7.080000e-03      0.000000
          services rural water tanks              -3.610000e-03      0.000000
          services urban decentral water tanks    -5.570000e-03      0.000000
          solid biomass                            1.365765e+09     13.658285
          urban central water tanks                3.321000e-02      0.000000

[106 rows x 12 columns]

In [54]:
n_KE_geo_pot_50res_50co2.statistics()

                                                   Optimal Capacity  \
Generator Combined-Cycle Gas                           6.391000e+02
          Geothermal                                   3.840014e+02
          Offshore Wind (AC)                           1.470000e-03
          Onshore Wind                                 1.718422e+04
          Run of River                                 3.562597e+02
...                                                             ...
Store     residential urban decentral water tanks      9.100000e-04
          services rural water tanks                   9.400000e-04
          services urban decentral water tanks         8.900000e-04
          solid biomass                                2.043000e+08
          urban central water tanks                    9.032000e-02

                                                   Installed Capacity  \
Generator Combined-Cycle Gas                             6.391000e+02
          Geothermal                                     3.840000e+02
          Offshore Wind (AC)                             0.000000e+00
          Onshore Wind                                   4.358154e+02
          Run of River                                   3.562597e+02
...                                                               ...
Store     residential urban decentral water tanks        0.000000e+00
          services rural water tanks                     0.000000e+00
          services urban decentral water tanks           0.000000e+00
          solid biomass                                  2.043000e+08
          urban central water tanks                      0.000000e+00

                                                         Supply  Withdrawal  \
Generator Combined-Cycle Gas                       4.502000e-01     0.00000
          Geothermal                               3.702995e+05     0.00000
          Offshore Wind (AC)                       2.125750e+00     0.00000
          Onshore Wind                             4.698540e+07     0.00000
          Run of River                             3.447298e+04     0.00000
...                                                         ...         ...
Store     residential urban decentral water tanks  0.000000e+00     0.02417
          services rural water tanks               0.000000e+00     0.02583
          services urban decentral water tanks     0.000000e+00     0.02312
          solid biomass                            9.999532e+07     0.00000
          urban central water tanks                3.570000e-03     0.09742

                                                   Energy Balance  \
Generator Combined-Cycle Gas                         4.502000e-01
          Geothermal                                 3.702995e+05
          Offshore Wind (AC)                         2.125750e+00
          Onshore Wind                               4.698540e+07
          Run of River                               3.447298e+04
...                                                           ...
Store     residential urban decentral water tanks   -2.417000e-02
          services rural water tanks                -2.583000e-02
          services urban decentral water tanks      -2.312000e-02
          solid biomass                              9.999532e+07
          urban central water tanks                 -9.386000e-02

                                                   Transmission  \
Generator Combined-Cycle Gas                                0.0
          Geothermal                                        0.0
          Offshore Wind (AC)                                0.0
          Onshore Wind                                      0.0
          Run of River                                      0.0
...                                                         ...
Store     residential urban decentral water tanks           0.0
          services rural water tanks                        0.0
          services urban decentral water tanks              0.0
          solid biomass                                     0.0
          urban central water tanks                         0.0

                                                   Capacity Factor  \
Generator Combined-Cycle Gas                          7.823502e-08
          Geothermal                                  1.100820e-01
          Offshore Wind (AC)                          1.632653e-01
          Onshore Wind                                3.121253e-01
          Run of River                                1.104607e-02
...                                                            ...
Store     residential urban decentral water tanks     5.054945e-01
          services rural water tanks                  5.212766e-01
          services urban decentral water tanks        4.943820e-01
          solid biomass                               7.625561e-01
          urban central water tanks                   5.211470e-01

                                                    Curtailment  \
Generator Combined-Cycle Gas                       5.598516e+06
          Geothermal                               1.883481e+06
          Offshore Wind (AC)                       1.155060e+00
          Onshore Wind                             8.574967e+06
          Run of River                             9.659967e+05
...                                                         ...
Store     residential urban decentral water tanks  0.000000e+00
          services rural water tanks               0.000000e+00
          services urban decentral water tanks     0.000000e+00
          solid biomass                            0.000000e+00
          urban central water tanks                0.000000e+00

                                                   Capital Expenditure  \
Generator Combined-Cycle Gas                              5.398422e+07
          Geothermal                                      7.378963e+07
          Offshore Wind (AC)                              2.893425e+02
          Onshore Wind                                    1.878159e+09
          Run of River                                    9.652526e+07
...                                                                ...
Store     residential urban decentral water tanks         5.552682e+02
          services rural water tanks                      5.715619e+02
          services urban decentral water tanks            5.444007e+02
          solid biomass                                   0.000000e+00
          urban central water tanks                       4.980856e+02

                                                   Operational Expenditure  \
Generator Combined-Cycle Gas                                  2.125389e+01
          Geothermal                                          3.555940e+03
          Offshore Wind (AC)                                  5.220000e-02
          Onshore Wind                                        1.146698e+06
          Run of River                                        3.511474e+02
...                                                                    ...
Store     residential urban decentral water tanks            -2.400000e-04
          services rural water tanks                         -2.600000e-04
          services urban decentral water tanks               -2.300000e-04
          solid biomass                                       1.365765e+09
          urban central water tanks                          -9.300000e-04

                                                        Revenue  Market Value
Generator Combined-Cycle Gas                      -9.160300e-01     -2.000000
          Geothermal                               9.376632e+05      2.532175
          Offshore Wind (AC)                      -7.606100e+00     -3.625000
          Onshore Wind                            -3.069237e+08     -6.532321
          Run of River                             1.689402e+05      4.900657
...                                                         ...           ...
Store     residential urban decentral water tanks -8.490000e-03      0.000000
          services rural water tanks              -4.200000e-03      0.000000
          services urban decentral water tanks    -6.580000e-03      0.000000
          solid biomass                            1.365765e+09     13.658285
          urban central water tanks                3.960000e-02      0.000000

[106 rows x 12 columns]

In [56]:
n_KE_geo_pot100res_100co2.statistics()

                                                   Optimal Capacity  \
Generator Combined-Cycle Gas                           6.391000e+02
          Geothermal                                   3.840015e+02
          Offshore Wind (AC)                           1.440000e-03
          Onshore Wind                                 1.529400e+05
          Run of River                                 3.562597e+02
...                                                             ...
Store     residential urban decentral water tanks      1.500000e-03
          services rural water tanks                   1.540000e-03
          services urban decentral water tanks         1.480000e-03
          solid biomass                                2.043000e+08
          urban central water tanks                    1.528200e-01

                                                   Installed Capacity  \
Generator Combined-Cycle Gas                             6.391000e+02
          Geothermal                                     3.840000e+02
          Offshore Wind (AC)                             0.000000e+00
          Onshore Wind                                   4.358154e+02
          Run of River                                   3.562597e+02
...                                                               ...
Store     residential urban decentral water tanks        0.000000e+00
          services rural water tanks                     0.000000e+00
          services urban decentral water tanks           0.000000e+00
          solid biomass                                  2.043000e+08
          urban central water tanks                      0.000000e+00

                                                         Supply  Withdrawal  \
Generator Combined-Cycle Gas                       6.166300e-01     0.00000
          Geothermal                               8.730855e+01     0.00000
          Offshore Wind (AC)                       2.048250e+00     0.00000
          Onshore Wind                             2.649213e+08     0.00000
          Run of River                             2.095032e+02     0.00000
...                                                         ...         ...
Store     residential urban decentral water tanks  0.000000e+00     0.03849
          services rural water tanks               0.000000e+00     0.04093
          services urban decentral water tanks     0.000000e+00     0.03725
          solid biomass                            9.983265e+07     0.00000
          urban central water tanks                1.170000e-03     0.15171

                                                   Energy Balance  \
Generator Combined-Cycle Gas                         6.166300e-01
          Geothermal                                 8.730855e+01
          Offshore Wind (AC)                         2.048250e+00
          Onshore Wind                               2.649213e+08
          Run of River                               2.095032e+02
...                                                           ...
Store     residential urban decentral water tanks   -3.849000e-02
          services rural water tanks                -4.093000e-02
          services urban decentral water tanks      -3.725000e-02
          solid biomass                              9.983265e+07
          urban central water tanks                 -1.505400e-01

                                                   Transmission  \
Generator Combined-Cycle Gas                                0.0
          Geothermal                                        0.0
          Offshore Wind (AC)                                0.0
          Onshore Wind                                      0.0
          Run of River                                      0.0
...                                                         ...
Store     residential urban decentral water tanks           0.0
          services rural water tanks                        0.0
          services urban decentral water tanks              0.0
          solid biomass                                     0.0
          urban central water tanks                         0.0

                                                   Capacity Factor  \
Generator Combined-Cycle Gas                          1.095290e-07
          Geothermal                                  2.596344e-05
          Offshore Wind (AC)                          1.597222e-01
          Onshore Wind                                1.977387e-01
          Run of River                                6.714203e-05
...                                                            ...
Store     residential urban decentral water tanks     4.866667e-01
          services rural water tanks                  5.064935e-01
          services urban decentral water tanks        4.797297e-01
          solid biomass                               7.629608e-01
          urban central water tanks                   4.939798e-01

                                                    Curtailment  \
Generator Combined-Cycle Gas                       5.598515e+06
          Geothermal                               2.253695e+06
          Offshore Wind (AC)                       1.130090e+00
          Onshore Wind                             2.325800e+08
          Run of River                             1.000260e+06
...                                                         ...
Store     residential urban decentral water tanks  0.000000e+00
          services rural water tanks               0.000000e+00
          services urban decentral water tanks     0.000000e+00
          solid biomass                            0.000000e+00
          urban central water tanks                0.000000e+00

                                                   Capital Expenditure  \
Generator Combined-Cycle Gas                              5.398422e+07
          Geothermal                                      7.378966e+07
          Offshore Wind (AC)                              2.854140e+02
          Onshore Wind                                    1.671566e+10
          Run of River                                    9.652526e+07
...                                                                ...
Store     residential urban decentral water tanks         9.128916e+02
          services rural water tanks                      9.362276e+02
          services urban decentral water tanks            9.003315e+02
          solid biomass                                   0.000000e+00
          urban central water tanks                       8.428016e+02

                                                   Operational Expenditure  \
Generator Combined-Cycle Gas                                  2.911131e+01
          Geothermal                                          8.392600e-01
          Offshore Wind (AC)                                  5.014000e-02
          Onshore Wind                                        6.465285e+06
          Run of River                                        2.116720e+00
...                                                                    ...
Store     residential urban decentral water tanks            -3.900000e-04
          services rural water tanks                         -4.100000e-04
          services urban decentral water tanks               -3.700000e-04
          solid biomass                                       1.363543e+09
          urban central water tanks                          -1.500000e-03

                                                        Revenue  Market Value
Generator Combined-Cycle Gas                      -1.443160e+00     -2.285714
          Geothermal                              -1.291959e+01     -0.147442
          Offshore Wind (AC)                      -8.834350e+00     -4.391304
          Onshore Wind                            -1.644539e+09     -6.207653
          Run of River                            -2.685309e+01     -0.128344
...                                                         ...           ...
Store     residential urban decentral water tanks -6.640000e-03      0.000000
          services rural water tanks              -2.230000e-03      0.000000
          services urban decentral water tanks    -2.820000e-03      0.000000
          solid biomass                            1.363543e+09     13.658285
          urban central water tanks                2.517000e-02      0.000000

[106 rows x 12 columns]

### Substations

In [ ]:
n.buses[n.buses.symbol=="substation"]

### Transmission

In [ ]:
n.plot(bus_sizes=0.01, link_widths=5)

### Line Analysis

In [ ]:
n.lines

Total line length

In [ ]:
n.lines.length.sum()

Total link length

In [ ]:
n.links.length.sum()